/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package io.code.gamedb;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Game extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3022519306413598403L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Game\",\"namespace\":\"io.code.gamedb\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"rating\",\"type\":\"float\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"manufacturer\",\"type\":\"string\"},{\"name\":\"genre\",\"type\":\"string\"},{\"name\":\"releaseDate\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Game> ENCODER =
      new BinaryMessageEncoder<Game>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Game> DECODER =
      new BinaryMessageDecoder<Game>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Game> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Game> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Game> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Game>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Game to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Game from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Game instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Game fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int id;
   private float rating;
   private java.lang.CharSequence name;
   private java.lang.CharSequence manufacturer;
   private java.lang.CharSequence genre;
   private java.lang.CharSequence releaseDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Game() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param rating The new value for rating
   * @param name The new value for name
   * @param manufacturer The new value for manufacturer
   * @param genre The new value for genre
   * @param releaseDate The new value for releaseDate
   */
  public Game(java.lang.Integer id, java.lang.Float rating, java.lang.CharSequence name, java.lang.CharSequence manufacturer, java.lang.CharSequence genre, java.lang.CharSequence releaseDate) {
    this.id = id;
    this.rating = rating;
    this.name = name;
    this.manufacturer = manufacturer;
    this.genre = genre;
    this.releaseDate = releaseDate;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return rating;
    case 2: return name;
    case 3: return manufacturer;
    case 4: return genre;
    case 5: return releaseDate;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: rating = (java.lang.Float)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    case 3: manufacturer = (java.lang.CharSequence)value$; break;
    case 4: genre = (java.lang.CharSequence)value$; break;
    case 5: releaseDate = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public int getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(int value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'rating' field.
   * @return The value of the 'rating' field.
   */
  public float getRating() {
    return rating;
  }


  /**
   * Sets the value of the 'rating' field.
   * @param value the value to set.
   */
  public void setRating(float value) {
    this.rating = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'manufacturer' field.
   * @return The value of the 'manufacturer' field.
   */
  public java.lang.CharSequence getManufacturer() {
    return manufacturer;
  }


  /**
   * Sets the value of the 'manufacturer' field.
   * @param value the value to set.
   */
  public void setManufacturer(java.lang.CharSequence value) {
    this.manufacturer = value;
  }

  /**
   * Gets the value of the 'genre' field.
   * @return The value of the 'genre' field.
   */
  public java.lang.CharSequence getGenre() {
    return genre;
  }


  /**
   * Sets the value of the 'genre' field.
   * @param value the value to set.
   */
  public void setGenre(java.lang.CharSequence value) {
    this.genre = value;
  }

  /**
   * Gets the value of the 'releaseDate' field.
   * @return The value of the 'releaseDate' field.
   */
  public java.lang.CharSequence getReleaseDate() {
    return releaseDate;
  }


  /**
   * Sets the value of the 'releaseDate' field.
   * @param value the value to set.
   */
  public void setReleaseDate(java.lang.CharSequence value) {
    this.releaseDate = value;
  }

  /**
   * Creates a new Game RecordBuilder.
   * @return A new Game RecordBuilder
   */
  public static io.code.gamedb.Game.Builder newBuilder() {
    return new io.code.gamedb.Game.Builder();
  }

  /**
   * Creates a new Game RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Game RecordBuilder
   */
  public static io.code.gamedb.Game.Builder newBuilder(io.code.gamedb.Game.Builder other) {
    if (other == null) {
      return new io.code.gamedb.Game.Builder();
    } else {
      return new io.code.gamedb.Game.Builder(other);
    }
  }

  /**
   * Creates a new Game RecordBuilder by copying an existing Game instance.
   * @param other The existing instance to copy.
   * @return A new Game RecordBuilder
   */
  public static io.code.gamedb.Game.Builder newBuilder(io.code.gamedb.Game other) {
    if (other == null) {
      return new io.code.gamedb.Game.Builder();
    } else {
      return new io.code.gamedb.Game.Builder(other);
    }
  }

  /**
   * RecordBuilder for Game instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Game>
    implements org.apache.avro.data.RecordBuilder<Game> {

    private int id;
    private float rating;
    private java.lang.CharSequence name;
    private java.lang.CharSequence manufacturer;
    private java.lang.CharSequence genre;
    private java.lang.CharSequence releaseDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(io.code.gamedb.Game.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.rating)) {
        this.rating = data().deepCopy(fields()[1].schema(), other.rating);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.manufacturer)) {
        this.manufacturer = data().deepCopy(fields()[3].schema(), other.manufacturer);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.genre)) {
        this.genre = data().deepCopy(fields()[4].schema(), other.genre);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.releaseDate)) {
        this.releaseDate = data().deepCopy(fields()[5].schema(), other.releaseDate);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing Game instance
     * @param other The existing instance to copy.
     */
    private Builder(io.code.gamedb.Game other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.rating)) {
        this.rating = data().deepCopy(fields()[1].schema(), other.rating);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.manufacturer)) {
        this.manufacturer = data().deepCopy(fields()[3].schema(), other.manufacturer);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.genre)) {
        this.genre = data().deepCopy(fields()[4].schema(), other.genre);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.releaseDate)) {
        this.releaseDate = data().deepCopy(fields()[5].schema(), other.releaseDate);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public int getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'rating' field.
      * @return The value.
      */
    public float getRating() {
      return rating;
    }


    /**
      * Sets the value of the 'rating' field.
      * @param value The value of 'rating'.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder setRating(float value) {
      validate(fields()[1], value);
      this.rating = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'rating' field has been set.
      * @return True if the 'rating' field has been set, false otherwise.
      */
    public boolean hasRating() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'rating' field.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder clearRating() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'manufacturer' field.
      * @return The value.
      */
    public java.lang.CharSequence getManufacturer() {
      return manufacturer;
    }


    /**
      * Sets the value of the 'manufacturer' field.
      * @param value The value of 'manufacturer'.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder setManufacturer(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.manufacturer = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'manufacturer' field has been set.
      * @return True if the 'manufacturer' field has been set, false otherwise.
      */
    public boolean hasManufacturer() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'manufacturer' field.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder clearManufacturer() {
      manufacturer = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'genre' field.
      * @return The value.
      */
    public java.lang.CharSequence getGenre() {
      return genre;
    }


    /**
      * Sets the value of the 'genre' field.
      * @param value The value of 'genre'.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder setGenre(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.genre = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'genre' field has been set.
      * @return True if the 'genre' field has been set, false otherwise.
      */
    public boolean hasGenre() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'genre' field.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder clearGenre() {
      genre = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'releaseDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getReleaseDate() {
      return releaseDate;
    }


    /**
      * Sets the value of the 'releaseDate' field.
      * @param value The value of 'releaseDate'.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder setReleaseDate(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.releaseDate = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'releaseDate' field has been set.
      * @return True if the 'releaseDate' field has been set, false otherwise.
      */
    public boolean hasReleaseDate() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'releaseDate' field.
      * @return This builder.
      */
    public io.code.gamedb.Game.Builder clearReleaseDate() {
      releaseDate = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Game build() {
      try {
        Game record = new Game();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.rating = fieldSetFlags()[1] ? this.rating : (java.lang.Float) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.manufacturer = fieldSetFlags()[3] ? this.manufacturer : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.genre = fieldSetFlags()[4] ? this.genre : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.releaseDate = fieldSetFlags()[5] ? this.releaseDate : (java.lang.CharSequence) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Game>
    WRITER$ = (org.apache.avro.io.DatumWriter<Game>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Game>
    READER$ = (org.apache.avro.io.DatumReader<Game>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.id);

    out.writeFloat(this.rating);

    out.writeString(this.name);

    out.writeString(this.manufacturer);

    out.writeString(this.genre);

    out.writeString(this.releaseDate);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readInt();

      this.rating = in.readFloat();

      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.manufacturer = in.readString(this.manufacturer instanceof Utf8 ? (Utf8)this.manufacturer : null);

      this.genre = in.readString(this.genre instanceof Utf8 ? (Utf8)this.genre : null);

      this.releaseDate = in.readString(this.releaseDate instanceof Utf8 ? (Utf8)this.releaseDate : null);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readInt();
          break;

        case 1:
          this.rating = in.readFloat();
          break;

        case 2:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 3:
          this.manufacturer = in.readString(this.manufacturer instanceof Utf8 ? (Utf8)this.manufacturer : null);
          break;

        case 4:
          this.genre = in.readString(this.genre instanceof Utf8 ? (Utf8)this.genre : null);
          break;

        case 5:
          this.releaseDate = in.readString(this.releaseDate instanceof Utf8 ? (Utf8)this.releaseDate : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










